theme = ["noteworthy"]

baseURL = "https://blog.brennan.sh/"
languageCode = "en-us"
title = "0x7CC"

enableRobotsTXT = true
summaryLength = 20 # Configure how long the post summary should be on the homepage.

[author]
	name = "Brennan"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[params]
	math = true
	# Blog description at the top of the homepage. Supports markdown.
	description = "Travel, Food, Tech, and Geodesy!"

  # Main
  email = "emailto:brennan.mcdonald.mail@gmail.com"
  twitter = "https://twitter.com/bmickeydonald"
  instagram = "https://instagram.com/brennanmcd"
  linkedin = "https://linkedin.com/in/brennan-mcdonald"

  # Programming
  github = "https://github.com/brennanmcdonald"

# Menu links along the sidebar navigation.

[[menu.main]]
  name = "My Personal Site"
  identifier = "homepage"
  url = "https://brennan.sh"
	weight = 1
  
[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about/"
	weight = 2 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
	identifier = "tags"
	name = "Tags"
	url = "/tags/"
	weight = 3

[[menu.main]]
	name = "Archives"
	identifier = "archives"
	url = "/archives/"
	weight = 4

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
